# Generated by Django 4.1.3 on 2022-12-21 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Category name', max_length=100)),
                ('slug', models.SlugField(help_text='URL', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='Product name', max_length=100)),
                ('slug', models.SlugField(help_text='URL', max_length=100, unique=True)),
                ('price', models.FloatField(default=0, help_text='Product price')),
                ('availability', models.BooleanField(default=True, help_text='Product availability')),
                ('description', models.CharField(default=None, help_text='Product description', max_length=500)),
                ('images', models.ImageField(default=None, help_text='Product images', upload_to='')),
                ('category', models.CharField(default=None, help_text='Product category', max_length=50)),
                ('brend', models.CharField(default=None, help_text='Product BREND', max_length=50)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.category')),
            ],
            options={
                'verbose_name': 'Коллекционные игрушки FUNKO',
                'verbose_name_plural': 'Коллекционные игрушки FUNKO',
                'ordering': ['name', 'cat'],
            },
        ),
    ]
